name: main

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.github/workflows/*'
    branches: [master]
    
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install mypy
        run: pip install mypy
